-- ScholarQ | Master OS Final Schema Patch
-- RUN THIS IN SUPABASE SQL EDITOR TO UNLOCK ALL FEATURES

-- 1. TRANSACTIONS TABLE (Points Ledger)
CREATE TABLE IF NOT EXISTS transactions (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  amount INTEGER NOT NULL,
  description TEXT NOT NULL,
  type TEXT NOT NULL -- 'EARN' or 'SPEND'
);

-- 2. MARKETPLACE TABLE (The Vault)
CREATE TABLE IF NOT EXISTS marketplace (
  id TEXT PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  title TEXT NOT NULL,
  price INTEGER NOT NULL,
  link TEXT NOT NULL,
  seller_id UUID REFERENCES users(id) ON DELETE CASCADE,
  seller_name TEXT NOT NULL
);

-- 3. USER PROFILE EXTENSIONS (For Gauntlet & Metrics)
ALTER TABLE users ADD COLUMN IF NOT EXISTS points INTEGER DEFAULT 50;
ALTER TABLE users ADD COLUMN IF NOT EXISTS streak INTEGER DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS trust_score INTEGER DEFAULT 75;
ALTER TABLE users ADD COLUMN IF NOT EXISTS multiplier DECIMAL DEFAULT 1.00;
ALTER TABLE users ADD COLUMN IF NOT EXISTS status_badge TEXT DEFAULT 'SCHOLAR';
ALTER TABLE users ADD COLUMN IF NOT EXISTS gauntlet_progress INTEGER DEFAULT 0;

-- 4. ENABLE RLS & POLICIES
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read/Write Transactions" ON transactions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Read/Write Marketplace" ON marketplace FOR ALL USING (true) WITH CHECK (true);
