-- ScholarQ | Utility Upgrade V116
-- RUN THIS IN SUPABASE SQL EDITOR

-- 1. BOOKMARKS TABLE
CREATE TABLE IF NOT EXISTS bookmarks (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  question_id TEXT REFERENCES questions(id) ON DELETE CASCADE,
  UNIQUE(user_id, question_id)
);

-- 2. ADD INSIGHTFUL TRACKING TO ANSWERS
ALTER TABLE answers ADD COLUMN IF NOT EXISTS insightful_count INTEGER DEFAULT 0;

-- 3. ENABLE RLS
ALTER TABLE bookmarks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read/Write Bookmarks" ON bookmarks FOR ALL USING (true) WITH CHECK (true);
